services:
  master-service-dev:
    build:
      context: ./master-service
      dockerfile: Dockerfile.dev
    container_name: master-service-dev
    ports:
      - "18082:8080"
    environment:
      RESUME_ANALYZER_BASE_URL: http://resume-analyzer-dev:8080
      CODING_ANALYZER_BASE_URL: http://coding-analyzer-dev:8080
      MARKSHEET_ANALYZER_BASE_URL: http://marksheet-analyzer-dev:8080
    depends_on:
      - resume-analyzer-dev
      - coding-analyzer-dev
    volumes:
      - ./master-service:/app
    restart: unless-stopped

  coding-analyzer-dev:
    build:
      context: ./coding-analyzer
      dockerfile: Dockerfile.dev
    container_name: coding-analyzer-dev
    ports:
      - "18080:8080"
    volumes:
      - ./coding-analyzer:/app
    restart: unless-stopped

  resume-analyzer-dev:
    build:
      context: ./resume-analyzer
      dockerfile: Dockerfile.dev
    container_name: resume-analyzer-dev
    ports:
      - "18081:8080"
    volumes:
      - ./resume-analyzer:/app
    restart: unless-stopped

  marksheet-analyzer-dev:
    build:
      context: ./marksheet-analyzer
      dockerfile: Dockerfile.dev
    container_name: marksheet-analyzer-dev
    ports:
      - "18083:8080"
    volumes:
      - ./marksheet-analyzer:/app
    restart: unless-stopped
