"""initial schema

Revision ID: 9abe0d339a24
Revises: 
Create Date: 2026-08-08 14:19:18.862948

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9abe0d339a24'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('roll_no', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=False),
    sa.Column('branch', sa.String(length=128), nullable=False),
    sa.Column('cgpa', sa.Float(), nullable=True),
    sa.Column('gender', sa.String(length=16), nullable=False),
    sa.Column('cgpa_verified', sa.Boolean(), nullable=False),
    sa.Column('has_active_backlog', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_students_backlog', 'students', ['has_active_backlog'], unique=False)
    op.create_index(op.f('ix_students_branch'), 'students', ['branch'], unique=False)
    op.create_index(op.f('ix_students_email'), 'students', ['email'], unique=True)
    op.create_index(op.f('ix_students_gender'), 'students', ['gender'], unique=False)
    op.create_index(op.f('ix_students_roll_no'), 'students', ['roll_no'], unique=True)
    op.create_table('tpo_analysis_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('jd_summary', sa.Text(), nullable=True),
    sa.Column('company_name', sa.String(length=255), nullable=True),
    sa.Column('role_type', sa.String(length=32), nullable=True),
    sa.Column('pay_or_stipend', sa.String(length=128), nullable=True),
    sa.Column('duration', sa.String(length=128), nullable=True),
    sa.Column('bond_details', sa.Text(), nullable=True),
    sa.Column('jd_topics', sa.JSON(), nullable=False),
    sa.Column('jd_key_points', sa.JSON(), nullable=False),
    sa.Column('interview_timezone', sa.String(length=64), nullable=True),
    sa.Column('total_rounds', sa.Integer(), nullable=False),
    sa.Column('current_round_no', sa.Integer(), nullable=False),
    sa.Column('round_state', sa.String(length=32), nullable=False),
    sa.Column('created_by', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tpo_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tpo_username', sa.String(length=128), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('contact_number', sa.String(length=32), nullable=True),
    sa.Column('institute_name', sa.String(length=255), nullable=True),
    sa.Column('sender_name', sa.String(length=255), nullable=True),
    sa.Column('reply_to_email', sa.String(length=255), nullable=True),
    sa.Column('default_timezone', sa.String(length=64), nullable=True),
    sa.Column('stale_group_reminder_enabled', sa.Boolean(), nullable=False),
    sa.Column('daily_queue_summary_enabled', sa.Boolean(), nullable=False),
    sa.Column('placement_update_confirmation_enabled', sa.Boolean(), nullable=False),
    sa.Column('tpo_password_hash', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tpo_settings_tpo_username'), 'tpo_settings', ['tpo_username'], unique=True)
    op.create_table('placement_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('offer_type', sa.String(length=32), nullable=False),
    sa.Column('pay_amount', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_placement_records_student_id'), 'placement_records', ['student_id'], unique=False)
    op.create_table('raw_uploads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('resume_url', sa.String(length=1024), nullable=True),
    sa.Column('marksheet_url', sa.String(length=1024), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_raw_uploads_student_id'), 'raw_uploads', ['student_id'], unique=False)
    op.create_index('ix_raw_uploads_student_uploaded', 'raw_uploads', ['student_id', 'uploaded_at', 'id'], unique=False)
    op.create_table('student_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('github_username', sa.String(length=128), nullable=True),
    sa.Column('leetcode_username', sa.String(length=128), nullable=True),
    sa.Column('skills', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('coding_persona', sa.String(length=128), nullable=False),
    sa.Column('coding_score', sa.Float(), nullable=False),
    sa.Column('academic_score', sa.Float(), nullable=False),
    sa.Column('overall_score', sa.Float(), nullable=False),
    sa.Column('github_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('leetcode_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('resume_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('academic_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('skills_json', sa.JSON(), nullable=False),
    sa.Column('last_analyzed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id')
    )
    op.create_index('ix_student_profiles_skills_gin', 'student_profiles', ['skills'], unique=False, postgresql_using='gin')
    op.create_index('ux_student_profiles_github_username', 'student_profiles', ['github_username'], unique=True)
    op.create_index('ux_student_profiles_leetcode_username', 'student_profiles', ['leetcode_username'], unique=True)
    op.create_table('tpo_analysis_group_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['tpo_analysis_groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tpo_analysis_group_members_group_id'), 'tpo_analysis_group_members', ['group_id'], unique=False)
    op.create_index(op.f('ix_tpo_analysis_group_members_student_id'), 'tpo_analysis_group_members', ['student_id'], unique=False)
    op.create_table('tpo_group_rounds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('round_no', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('finalized_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['tpo_analysis_groups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tpo_group_rounds_group_id'), 'tpo_group_rounds', ['group_id'], unique=False)
    op.create_index('ux_tpo_group_round_unique', 'tpo_group_rounds', ['group_id', 'round_no'], unique=True)
    op.create_table('tpo_mail_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('requested_by', sa.String(length=128), nullable=False),
    sa.Column('mail_type', sa.String(length=64), nullable=False),
    sa.Column('round_no', sa.Integer(), nullable=True),
    sa.Column('outcome', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('total_recipients', sa.Integer(), nullable=False),
    sa.Column('processed_count', sa.Integer(), nullable=False),
    sa.Column('success_count', sa.Integer(), nullable=False),
    sa.Column('failure_count', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['tpo_analysis_groups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tpo_mail_jobs_group_id'), 'tpo_mail_jobs', ['group_id'], unique=False)
    op.create_index(op.f('ix_tpo_mail_jobs_round_no'), 'tpo_mail_jobs', ['round_no'], unique=False)
    op.create_index(op.f('ix_tpo_mail_jobs_status'), 'tpo_mail_jobs', ['status'], unique=False)
    op.create_table('tpo_group_round_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('round_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['round_id'], ['tpo_group_rounds.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tpo_group_round_members_round_id'), 'tpo_group_round_members', ['round_id'], unique=False)
    op.create_index(op.f('ix_tpo_group_round_members_student_id'), 'tpo_group_round_members', ['student_id'], unique=False)
    op.create_index('ux_tpo_group_round_member_unique', 'tpo_group_round_members', ['round_id', 'student_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ux_tpo_group_round_member_unique', table_name='tpo_group_round_members')
    op.drop_index(op.f('ix_tpo_group_round_members_student_id'), table_name='tpo_group_round_members')
    op.drop_index(op.f('ix_tpo_group_round_members_round_id'), table_name='tpo_group_round_members')
    op.drop_table('tpo_group_round_members')
    op.drop_index(op.f('ix_tpo_mail_jobs_status'), table_name='tpo_mail_jobs')
    op.drop_index(op.f('ix_tpo_mail_jobs_round_no'), table_name='tpo_mail_jobs')
    op.drop_index(op.f('ix_tpo_mail_jobs_group_id'), table_name='tpo_mail_jobs')
    op.drop_table('tpo_mail_jobs')
    op.drop_index('ux_tpo_group_round_unique', table_name='tpo_group_rounds')
    op.drop_index(op.f('ix_tpo_group_rounds_group_id'), table_name='tpo_group_rounds')
    op.drop_table('tpo_group_rounds')
    op.drop_index(op.f('ix_tpo_analysis_group_members_student_id'), table_name='tpo_analysis_group_members')
    op.drop_index(op.f('ix_tpo_analysis_group_members_group_id'), table_name='tpo_analysis_group_members')
    op.drop_table('tpo_analysis_group_members')
    op.drop_index('ux_student_profiles_leetcode_username', table_name='student_profiles')
    op.drop_index('ux_student_profiles_github_username', table_name='student_profiles')
    op.drop_index('ix_student_profiles_skills_gin', table_name='student_profiles', postgresql_using='gin')
    op.drop_table('student_profiles')
    op.drop_index('ix_raw_uploads_student_uploaded', table_name='raw_uploads')
    op.drop_index(op.f('ix_raw_uploads_student_id'), table_name='raw_uploads')
    op.drop_table('raw_uploads')
    op.drop_index(op.f('ix_placement_records_student_id'), table_name='placement_records')
    op.drop_table('placement_records')
    op.drop_index(op.f('ix_tpo_settings_tpo_username'), table_name='tpo_settings')
    op.drop_table('tpo_settings')
    op.drop_table('tpo_analysis_groups')
    op.drop_index(op.f('ix_students_roll_no'), table_name='students')
    op.drop_index(op.f('ix_students_gender'), table_name='students')
    op.drop_index(op.f('ix_students_email'), table_name='students')
    op.drop_index(op.f('ix_students_branch'), table_name='students')
    op.drop_index('ix_students_backlog', table_name='students')
    op.drop_table('students')
    # ### end Alembic commands ###
