from __future__ import annotations

from datetime import UTC, datetime
import hashlib
import random

from sqlalchemy import text

from app.database.database import SessionLocal
from app.database.models import RawUpload, Student, StudentProfile

DEMO_STUDENTS: list[dict] = [
    {
        "name": 'Aarav Sharma',
        "email": 'aarav.sharma.demo@verifai.dev',
        "phone": '+919910000001',
        "roll_no": 'AKTU-CSE-001',
        "branch": 'CSE',
        "cgpa": 8.6,
        "gender": 'men',
        "skills": ['python', 'c++', 'dsa', 'problem solving'],
        "coding_persona": 'competitive',
        "coding_score": 58.9,
        "academic_score": 84.2,
        "overall_score": 69.0,
        "has_active_backlog": False,
        "is_placed": False,
        "resume_url": 'https://demo-resumes.verifai.dev/aarav-sharma.pdf',
    },
    {
        "name": 'Isha Verma',
        "email": 'isha.verma.demo@verifai.dev',
        "phone": '+919910000002',
        "roll_no": 'AKTU-IT-002',
        "branch": 'IT',
        "cgpa": 7.2,
        "gender": 'women',
        "skills": ['javascript', 'react', 'node.js', 'mongodb'],
        "coding_persona": 'full_stack',
        "coding_score": 83.0,
        "academic_score": 73.4,
        "overall_score": 79.2,
        "has_active_backlog": False,
        "is_placed": False,
        "resume_url": 'https://demo-resumes.verifai.dev/isha-verma.pdf',
    },
    {
        "name": 'Neel Rao',
        "email": 'neel.rao.demo@verifai.dev',
        "phone": '+919910000003',
        "roll_no": 'AKTU-AIML-003',
        "branch": 'AIML',
        "cgpa": 9.4,
        "gender": 'other',
        "skills": ['python', 'django', 'postgresql', 'redis'],
        "coding_persona": 'backend',
        "coding_score": 61.0,
        "academic_score": 93.4,
        "overall_score": 74.0,
        "has_active_backlog": False,
        "is_placed": False,
        "resume_url": 'https://demo-resumes.verifai.dev/neel-rao.pdf',
    },
    {
        "name": 'Sneha Singh',
        "email": 'sneha.singh.demo@verifai.dev',
        "phone": '+919910000004',
        "roll_no": 'AKTU-DS-004',
        "branch": 'DS',
        "cgpa": 6.5,
        "gender": 'women',
        "skills": ['python', 'sql', 'data analysis', 'power bi'],
        "coding_persona": 'data_analyst',
        "coding_score": 65.4,
        "academic_score": 65.0,
        "overall_score": 65.2,
        "has_active_backlog": True,
        "is_placed": False,
        "resume_url": 'https://demo-resumes.verifai.dev/sneha-singh.pdf',
    },
    {
        "name": 'Rahul Yadav',
        "email": 'rahul.yadav.demo@verifai.dev',
        "phone": '+919910000005',
        "roll_no": 'AKTU-EEE-005',
        "branch": 'EEE',
        "cgpa": 6.5,
        "gender": 'men',
        "skills": ['embedded c', 'arduino', 'sensors', 'pcb design'],
        "coding_persona": 'iot_builder',
        "coding_score": 64.8,
        "academic_score": 66.2,
        "overall_score": 65.4,
        "has_active_backlog": True,
        "is_placed": False,
        "resume_url": 'https://demo-resumes.verifai.dev/rahul-yadav.pdf',
    },
    {
        "name": 'Pooja Nair',
        "email": 'pooja.nair.demo@verifai.dev',
        "phone": '+919910000006',
        "roll_no": 'AKTU-ME-006',
        "branch": 'ME',
        "cgpa": 8.3,
        "gender": 'women',
        "skills": ['excel', 'communication', 'process improvement', 'power bi'],
        "coding_persona": 'operations',
        "coding_score": 65.5,
        "academic_score": 83.7,
        "overall_score": 72.8,
        "has_active_backlog": False,
        "is_placed": False,
        "resume_url": 'https://demo-resumes.verifai.dev/pooja-nair.pdf',
    },
    {
        "name": 'Aditya Mehra',
        "email": 'aditya.mehra.demo@verifai.dev',
        "phone": '+919910000007',
        "roll_no": 'AKTU-ECE-007',
        "branch": 'ECE',
        "cgpa": 9.2,
        "gender": 'men',
        "skills": ['embedded c', 'microcontrollers', 'rtos', 'pcb design'],
        "coding_persona": 'embedded',
        "coding_score": 58.2,
        "academic_score": 94.4,
        "overall_score": 72.7,
        "has_active_backlog": False,
        "is_placed": False,
        "resume_url": 'https://demo-resumes.verifai.dev/aditya-mehra.pdf',
    },
    {
        "name": 'Kavya Iyer',
        "email": 'kavya.iyer.demo@verifai.dev',
        "phone": '+919910000008',
        "roll_no": 'AKTU-CE-008',
        "branch": 'CE',
        "cgpa": 8.8,
        "gender": 'women',
        "skills": ['project management', 'notion', 'communication', 'analytics'],
        "coding_persona": 'product_builder',
        "coding_score": 69.6,
        "academic_score": 85.2,
        "overall_score": 75.8,
        "has_active_backlog": False,
        "is_placed": False,
        "resume_url": 'https://demo-resumes.verifai.dev/kavya-iyer.pdf',
    },
    {
        "name": 'Rohan Gupta',
        "email": 'rohan.gupta.demo@verifai.dev',
        "phone": '+919910000009',
        "roll_no": 'AKTU-CSE-009',
        "branch": 'CSE',
        "cgpa": 9.7,
        "gender": 'men',
        "skills": ['javascript', 'react', 'node.js', 'mongodb'],
        "coding_persona": 'full_stack',
        "coding_score": 69.4,
        "academic_score": 93.7,
        "overall_score": 79.1,
        "has_active_backlog": False,
        "is_placed": True,
        "resume_url": 'https://demo-resumes.verifai.dev/rohan-gupta.pdf',
    },
    {
        "name": 'Meera Joshi',
        "email": 'meera.joshi.demo@verifai.dev',
        "phone": '+919910000010',
        "roll_no": 'AKTU-IT-010',
        "branch": 'IT',
        "cgpa": 6.7,
        "gender": 'women',
        "skills": ['javascript', 'react', 'ui/ux design', 'figma'],
        "coding_persona": 'frontend',
        "coding_score": 86.8,
        "academic_score": 67.8,
        "overall_score": 79.2,
        "has_active_backlog": True,
        "is_placed": False,
        "resume_url": 'https://demo-resumes.verifai.dev/meera-joshi.pdf',
    },
    {
        "name": 'Arjun Patel',
        "email": 'arjun.patel.demo@verifai.dev',
        "phone": '+919910000011',
        "roll_no": 'AKTU-AIML-011',
        "branch": 'AIML',
        "cgpa": 9.1,
        "gender": 'men',
        "skills": ['python', 'pandas', 'scikit-learn', 'sql'],
        "coding_persona": 'data_scientist',
        "coding_score": 82.8,
        "academic_score": 91.3,
        "overall_score": 86.2,
        "has_active_backlog": True,
        "is_placed": False,
        "resume_url": 'https://demo-resumes.verifai.dev/arjun-patel.pdf',
    },
    {
        "name": 'Diya Kapoor',
        "email": 'diya.kapoor.demo@verifai.dev',
        "phone": '+919910000012',
        "roll_no": 'AKTU-DS-012',
        "branch": 'DS',
        "cgpa": 9.7,
        "gender": 'women',
        "skills": ['python', 'statistics', 'nlp', 'literature review'],
        "coding_persona": 'research',
        "coding_score": 70.9,
        "academic_score": 95,
        "overall_score": 80.5,
        "has_active_backlog": False,
        "is_placed": True,
        "resume_url": 'https://demo-resumes.verifai.dev/diya-kapoor.pdf',
    },
    {
        "name": 'Vivek Kumar',
        "email": 'vivek.kumar.demo@verifai.dev',
        "phone": '+919910000013',
        "roll_no": 'AKTU-EEE-013',
        "branch": 'EEE',
        "cgpa": 9.2,
        "gender": 'men',
        "skills": ['matlab', 'autocad', 'problem solving', 'technical documentation'],
        "coding_persona": 'core_engineering',
        "coding_score": 79.0,
        "academic_score": 94.9,
        "overall_score": 85.4,
        "has_active_backlog": False,
        "is_placed": True,
        "resume_url": 'https://demo-resumes.verifai.dev/vivek-kumar.pdf',
    },
    {
        "name": 'Ananya Das',
        "email": 'ananya.das.demo@verifai.dev',
        "phone": '+919910000014',
        "roll_no": 'AKTU-ME-014',
        "branch": 'ME',
        "cgpa": 8.4,
        "gender": 'women',
        "skills": ['matlab', 'autocad', 'problem solving', 'technical documentation'],
        "coding_persona": 'core_engineering',
        "coding_score": 82.0,
        "academic_score": 80.4,
        "overall_score": 81.4,
        "has_active_backlog": False,
        "is_placed": False,
        "resume_url": 'https://demo-resumes.verifai.dev/ananya-das.pdf',
    },
    {
        "name": 'Siddharth Jain',
        "email": 'siddharth.jain.demo@verifai.dev',
        "phone": '+919910000015',
        "roll_no": 'AKTU-ECE-015',
        "branch": 'ECE',
        "cgpa": 7.2,
        "gender": 'men',
        "skills": ['python', 'django', 'postgresql', 'redis'],
        "coding_persona": 'backend',
        "coding_score": 67.8,
        "academic_score": 68.6,
        "overall_score": 68.1,
        "has_active_backlog": False,
        "is_placed": False,
        "resume_url": 'https://demo-resumes.verifai.dev/siddharth-jain.pdf',
    },
    {
        "name": 'Ritika Sethi',
        "email": 'ritika.sethi.demo@verifai.dev',
        "phone": '+919910000016',
        "roll_no": 'AKTU-CE-016',
        "branch": 'CE',
        "cgpa": 7.2,
        "gender": 'women',
        "skills": ['excel', 'communication', 'process improvement', 'power bi'],
        "coding_persona": 'operations',
        "coding_score": 61.4,
        "academic_score": 70.2,
        "overall_score": 64.9,
        "has_active_backlog": False,
        "is_placed": False,
        "resume_url": 'https://demo-resumes.verifai.dev/ritika-sethi.pdf',
    },
    {
        "name": 'Harsh Vardhan',
        "email": 'harsh.vardhan.demo@verifai.dev',
        "phone": '+919910000017',
        "roll_no": 'AKTU-CSE-017',
        "branch": 'CSE',
        "cgpa": 8.6,
        "gender": 'men',
        "skills": ['python', 'django', 'postgresql', 'redis'],
        "coding_persona": 'backend',
        "coding_score": 70.4,
        "academic_score": 85.0,
        "overall_score": 76.2,
        "has_active_backlog": False,
        "is_placed": False,
        "resume_url": 'https://demo-resumes.verifai.dev/harsh-vardhan.pdf',
    },
    {
        "name": 'Tanvi Bansal',
        "email": 'tanvi.bansal.demo@verifai.dev',
        "phone": '+919910000018',
        "roll_no": 'AKTU-IT-018',
        "branch": 'IT',
        "cgpa": 7.1,
        "gender": 'women',
        "skills": ['project management', 'notion', 'communication', 'analytics'],
        "coding_persona": 'product_builder',
        "coding_score": 67.1,
        "academic_score": 74.5,
        "overall_score": 70.1,
        "has_active_backlog": True,
        "is_placed": False,
        "resume_url": 'https://demo-resumes.verifai.dev/tanvi-bansal.pdf',
    },
    {
        "name": 'Pranav Kulkarni',
        "email": 'pranav.kulkarni.demo@verifai.dev',
        "phone": '+919910000019',
        "roll_no": 'AKTU-AIML-019',
        "branch": 'AIML',
        "cgpa": 8.6,
        "gender": 'men',
        "skills": ['python', 'pytorch', 'mlops', 'docker'],
        "coding_persona": 'ml_engineer',
        "coding_score": 78.7,
        "academic_score": 83.4,
        "overall_score": 80.6,
        "has_active_backlog": False,
        "is_placed": False,
        "resume_url": 'https://demo-resumes.verifai.dev/pranav-kulkarni.pdf',
    },
    {
        "name": 'Nidhi Chauhan',
        "email": 'nidhi.chauhan.demo@verifai.dev',
        "phone": '+919910000020',
        "roll_no": 'AKTU-DS-020',
        "branch": 'DS',
        "cgpa": 8.9,
        "gender": 'women',
        "skills": ['python', 'pytorch', 'mlops', 'docker'],
        "coding_persona": 'ml_engineer',
        "coding_score": 63.6,
        "academic_score": 88.0,
        "overall_score": 73.4,
        "has_active_backlog": False,
        "is_placed": False,
        "resume_url": 'https://demo-resumes.verifai.dev/nidhi-chauhan.pdf',
    },
    {
        "name": 'Yash Malhotra',
        "email": 'yash.malhotra.demo@verifai.dev',
        "phone": '+919910000021',
        "roll_no": 'AKTU-EEE-021',
        "branch": 'EEE',
        "cgpa": 9.8,
        "gender": 'men',
        "skills": ['embedded c', 'microcontrollers', 'rtos', 'pcb design'],
        "coding_persona": 'embedded',
        "coding_score": 79.8,
        "academic_score": 95,
        "overall_score": 85.9,
        "has_active_backlog": False,
        "is_placed": True,
        "resume_url": 'https://demo-resumes.verifai.dev/yash-malhotra.pdf',
    },
    {
        "name": 'Aditi Mishra',
        "email": 'aditi.mishra.demo@verifai.dev',
        "phone": '+919910000022',
        "roll_no": 'AKTU-ME-022',
        "branch": 'ME',
        "cgpa": 8.7,
        "gender": 'women',
        "skills": ['project management', 'notion', 'communication', 'analytics'],
        "coding_persona": 'product_builder',
        "coding_score": 86.7,
        "academic_score": 89.2,
        "overall_score": 87.7,
        "has_active_backlog": True,
        "is_placed": False,
        "resume_url": 'https://demo-resumes.verifai.dev/aditi-mishra.pdf',
    },
    {
        "name": 'Manav Arora',
        "email": 'manav.arora.demo@verifai.dev',
        "phone": '+919910000023',
        "roll_no": 'AKTU-ECE-023',
        "branch": 'ECE',
        "cgpa": 7.2,
        "gender": 'men',
        "skills": ['embedded c', 'arduino', 'sensors', 'pcb design'],
        "coding_persona": 'iot_builder',
        "coding_score": 59.1,
        "academic_score": 70.5,
        "overall_score": 63.7,
        "has_active_backlog": False,
        "is_placed": False,
        "resume_url": 'https://demo-resumes.verifai.dev/manav-arora.pdf',
    },
    {
        "name": 'Sanya Thomas',
        "email": 'sanya.thomas.demo@verifai.dev',
        "phone": '+919910000024',
        "roll_no": 'AKTU-CE-024',
        "branch": 'CE',
        "cgpa": 7.3,
        "gender": 'women',
        "skills": ['python', 'sql', 'data analysis', 'power bi'],
        "coding_persona": 'data_analyst',
        "coding_score": 65.2,
        "academic_score": 76.5,
        "overall_score": 69.7,
        "has_active_backlog": False,
        "is_placed": False,
        "resume_url": 'https://demo-resumes.verifai.dev/sanya-thomas.pdf',
    },
    {
        "name": 'Karan Bhatia',
        "email": 'karan.bhatia.demo@verifai.dev',
        "phone": '+919910000025',
        "roll_no": 'AKTU-CSE-025',
        "branch": 'CSE',
        "cgpa": 9.4,
        "gender": 'men',
        "skills": ['python', 'c++', 'dsa', 'problem solving'],
        "coding_persona": 'competitive',
        "coding_score": 68.7,
        "academic_score": 95,
        "overall_score": 79.2,
        "has_active_backlog": False,
        "is_placed": True,
        "resume_url": 'https://demo-resumes.verifai.dev/karan-bhatia.pdf',
    },
    {
        "name": 'Shruti Menon',
        "email": 'shruti.menon.demo@verifai.dev',
        "phone": '+919910000026',
        "roll_no": 'AKTU-IT-026',
        "branch": 'IT',
        "cgpa": 7.7,
        "gender": 'women',
        "skills": ['javascript', 'react', 'node.js', 'mongodb'],
        "coding_persona": 'full_stack',
        "coding_score": 89.1,
        "academic_score": 76.7,
        "overall_score": 84.1,
        "has_active_backlog": False,
        "is_placed": False,
        "resume_url": 'https://demo-resumes.verifai.dev/shruti-menon.pdf',
    },
    {
        "name": 'Devansh Saxena',
        "email": 'devansh.saxena.demo@verifai.dev',
        "phone": '+919910000027',
        "roll_no": 'AKTU-AIML-027',
        "branch": 'AIML',
        "cgpa": 7.3,
        "gender": 'men',
        "skills": ['python', 'django', 'postgresql', 'redis'],
        "coding_persona": 'backend',
        "coding_score": 66.4,
        "academic_score": 73.5,
        "overall_score": 69.2,
        "has_active_backlog": False,
        "is_placed": False,
        "resume_url": 'https://demo-resumes.verifai.dev/devansh-saxena.pdf',
    },
    {
        "name": 'Palak Arvind',
        "email": 'palak.arvind.demo@verifai.dev',
        "phone": '+919910000028',
        "roll_no": 'AKTU-DS-028',
        "branch": 'DS',
        "cgpa": 7.3,
        "gender": 'women',
        "skills": ['python', 'sql', 'data analysis', 'power bi'],
        "coding_persona": 'data_analyst',
        "coding_score": 77.9,
        "academic_score": 76.2,
        "overall_score": 77.2,
        "has_active_backlog": False,
        "is_placed": False,
        "resume_url": 'https://demo-resumes.verifai.dev/palak-arvind.pdf',
    },
    {
        "name": 'Aman Tiwari',
        "email": 'aman.tiwari.demo@verifai.dev',
        "phone": '+919910000029',
        "roll_no": 'AKTU-EEE-029',
        "branch": 'EEE',
        "cgpa": 7.8,
        "gender": 'men',
        "skills": ['embedded c', 'arduino', 'sensors', 'pcb design'],
        "coding_persona": 'iot_builder',
        "coding_score": 65.5,
        "academic_score": 82.0,
        "overall_score": 72.1,
        "has_active_backlog": False,
        "is_placed": False,
        "resume_url": 'https://demo-resumes.verifai.dev/aman-tiwari.pdf',
    },
    {
        "name": 'Simran Kaur',
        "email": 'simran.kaur.demo@verifai.dev',
        "phone": '+919910000030',
        "roll_no": 'AKTU-ME-030',
        "branch": 'ME',
        "cgpa": 8.1,
        "gender": 'women',
        "skills": ['excel', 'communication', 'process improvement', 'power bi'],
        "coding_persona": 'operations',
        "coding_score": 61.1,
        "academic_score": 77.4,
        "overall_score": 67.6,
        "has_active_backlog": False,
        "is_placed": False,
        "resume_url": 'https://demo-resumes.verifai.dev/simran-kaur.pdf',
    },
    {
        "name": 'Rajat Srivastava',
        "email": 'rajat.srivastava.demo@verifai.dev',
        "phone": '+919910000031',
        "roll_no": 'AKTU-ECE-031',
        "branch": 'ECE',
        "cgpa": 6.8,
        "gender": 'men',
        "skills": ['embedded c', 'microcontrollers', 'rtos', 'pcb design'],
        "coding_persona": 'embedded',
        "coding_score": 79.3,
        "academic_score": 70.3,
        "overall_score": 75.7,
        "has_active_backlog": True,
        "is_placed": False,
        "resume_url": 'https://demo-resumes.verifai.dev/rajat-srivastava.pdf',
    },
    {
        "name": 'Muskan Ali',
        "email": 'muskan.ali.demo@verifai.dev',
        "phone": '+919910000032',
        "roll_no": 'AKTU-CE-032',
        "branch": 'CE',
        "cgpa": 7.8,
        "gender": 'women',
        "skills": ['project management', 'notion', 'communication', 'analytics'],
        "coding_persona": 'product_builder',
        "coding_score": 60.2,
        "academic_score": 77.1,
        "overall_score": 67.0,
        "has_active_backlog": False,
        "is_placed": False,
        "resume_url": 'https://demo-resumes.verifai.dev/muskan-ali.pdf',
    },
    {
        "name": 'Ayush Tripathi',
        "email": 'ayush.tripathi.demo@verifai.dev',
        "phone": '+919910000033',
        "roll_no": 'AKTU-CSE-033',
        "branch": 'CSE',
        "cgpa": 9.8,
        "gender": 'men',
        "skills": ['javascript', 'react', 'node.js', 'mongodb'],
        "coding_persona": 'full_stack',
        "coding_score": 76.0,
        "academic_score": 95,
        "overall_score": 83.6,
        "has_active_backlog": True,
        "is_placed": False,
        "resume_url": 'https://demo-resumes.verifai.dev/ayush-tripathi.pdf',
    },
    {
        "name": 'Ira Sen',
        "email": 'ira.sen.demo@verifai.dev',
        "phone": '+919910000034',
        "roll_no": 'AKTU-IT-034',
        "branch": 'IT',
        "cgpa": 9.3,
        "gender": 'women',
        "skills": ['javascript', 'react', 'ui/ux design', 'figma'],
        "coding_persona": 'frontend',
        "coding_score": 58.4,
        "academic_score": 94.8,
        "overall_score": 73.0,
        "has_active_backlog": False,
        "is_placed": False,
        "resume_url": 'https://demo-resumes.verifai.dev/ira-sen.pdf',
    },
    {
        "name": 'Dhruv Goel',
        "email": 'dhruv.goel.demo@verifai.dev',
        "phone": '+919910000035',
        "roll_no": 'AKTU-AIML-035',
        "branch": 'AIML',
        "cgpa": 8.7,
        "gender": 'men',
        "skills": ['python', 'pandas', 'scikit-learn', 'sql'],
        "coding_persona": 'data_scientist',
        "coding_score": 76.3,
        "academic_score": 85.1,
        "overall_score": 79.8,
        "has_active_backlog": False,
        "is_placed": False,
        "resume_url": 'https://demo-resumes.verifai.dev/dhruv-goel.pdf',
    },
    {
        "name": 'Rhea Dutta',
        "email": 'rhea.dutta.demo@verifai.dev',
        "phone": '+919910000036',
        "roll_no": 'AKTU-DS-036',
        "branch": 'DS',
        "cgpa": 8.6,
        "gender": 'women',
        "skills": ['python', 'statistics', 'nlp', 'literature review'],
        "coding_persona": 'research',
        "coding_score": 61.8,
        "academic_score": 85.5,
        "overall_score": 71.3,
        "has_active_backlog": False,
        "is_placed": False,
        "resume_url": 'https://demo-resumes.verifai.dev/rhea-dutta.pdf',
    },
    {
        "name": 'Naman Aggarwal',
        "email": 'naman.aggarwal.demo@verifai.dev',
        "phone": '+919910000037',
        "roll_no": 'AKTU-EEE-037',
        "branch": 'EEE',
        "cgpa": 7.9,
        "gender": 'men',
        "skills": ['matlab', 'autocad', 'problem solving', 'technical documentation'],
        "coding_persona": 'core_engineering',
        "coding_score": 90.4,
        "academic_score": 82.0,
        "overall_score": 87.0,
        "has_active_backlog": False,
        "is_placed": True,
        "resume_url": 'https://demo-resumes.verifai.dev/naman-aggarwal.pdf',
    },
    {
        "name": 'Vidhi Shah',
        "email": 'vidhi.shah.demo@verifai.dev',
        "phone": '+919910000038',
        "roll_no": 'AKTU-ME-038',
        "branch": 'ME',
        "cgpa": 7.3,
        "gender": 'women',
        "skills": ['matlab', 'autocad', 'problem solving', 'technical documentation'],
        "coding_persona": 'core_engineering',
        "coding_score": 75.0,
        "academic_score": 70.4,
        "overall_score": 73.2,
        "has_active_backlog": False,
        "is_placed": False,
        "resume_url": 'https://demo-resumes.verifai.dev/vidhi-shah.pdf',
    },
    {
        "name": 'Lakshya Puri',
        "email": 'lakshya.puri.demo@verifai.dev',
        "phone": '+919910000039',
        "roll_no": 'AKTU-ECE-039',
        "branch": 'ECE',
        "cgpa": 9.5,
        "gender": 'men',
        "skills": ['python', 'django', 'postgresql', 'redis'],
        "coding_persona": 'backend',
        "coding_score": 87.6,
        "academic_score": 93.4,
        "overall_score": 89.9,
        "has_active_backlog": False,
        "is_placed": False,
        "resume_url": 'https://demo-resumes.verifai.dev/lakshya-puri.pdf',
    },
    {
        "name": 'Mitali Roy',
        "email": 'mitali.roy.demo@verifai.dev',
        "phone": '+919910000040',
        "roll_no": 'AKTU-CE-040',
        "branch": 'CE',
        "cgpa": 8.6,
        "gender": 'women',
        "skills": ['excel', 'communication', 'process improvement', 'power bi'],
        "coding_persona": 'operations',
        "coding_score": 78.7,
        "academic_score": 83.2,
        "overall_score": 80.5,
        "has_active_backlog": False,
        "is_placed": True,
        "resume_url": 'https://demo-resumes.verifai.dev/mitali-roy.pdf',
    },
    {
        "name": 'Shivam Pandey',
        "email": 'shivam.pandey.demo@verifai.dev',
        "phone": '+919910000041',
        "roll_no": 'AKTU-CSE-041',
        "branch": 'CSE',
        "cgpa": 9.0,
        "gender": 'men',
        "skills": ['python', 'django', 'postgresql', 'redis'],
        "coding_persona": 'backend',
        "coding_score": 76.3,
        "academic_score": 92.2,
        "overall_score": 82.7,
        "has_active_backlog": False,
        "is_placed": True,
        "resume_url": 'https://demo-resumes.verifai.dev/shivam-pandey.pdf',
    },
    {
        "name": 'Esha Narang',
        "email": 'esha.narang.demo@verifai.dev',
        "phone": '+919910000042',
        "roll_no": 'AKTU-IT-042',
        "branch": 'IT',
        "cgpa": 8.2,
        "gender": 'women',
        "skills": ['project management', 'notion', 'communication', 'analytics'],
        "coding_persona": 'product_builder',
        "coding_score": 58.0,
        "academic_score": 80.6,
        "overall_score": 67.0,
        "has_active_backlog": False,
        "is_placed": False,
        "resume_url": 'https://demo-resumes.verifai.dev/esha-narang.pdf',
    },
    {
        "name": 'Om Prakash',
        "email": 'om.prakash.demo@verifai.dev',
        "phone": '+919910000043',
        "roll_no": 'AKTU-AIML-043',
        "branch": 'AIML',
        "cgpa": 6.5,
        "gender": 'men',
        "skills": ['python', 'pytorch', 'mlops', 'docker'],
        "coding_persona": 'ml_engineer',
        "coding_score": 89.6,
        "academic_score": 68.0,
        "overall_score": 81.0,
        "has_active_backlog": True,
        "is_placed": False,
        "resume_url": 'https://demo-resumes.verifai.dev/om-prakash.pdf',
    },
    {
        "name": 'Tanya Gill',
        "email": 'tanya.gill.demo@verifai.dev',
        "phone": '+919910000044',
        "roll_no": 'AKTU-DS-044',
        "branch": 'DS',
        "cgpa": 9.2,
        "gender": 'women',
        "skills": ['python', 'pytorch', 'mlops', 'docker'],
        "coding_persona": 'ml_engineer',
        "coding_score": 68.5,
        "academic_score": 88.5,
        "overall_score": 76.5,
        "has_active_backlog": True,
        "is_placed": False,
        "resume_url": 'https://demo-resumes.verifai.dev/tanya-gill.pdf',
    },
    {
        "name": 'Krish Chawla',
        "email": 'krish.chawla.demo@verifai.dev',
        "phone": '+919910000045',
        "roll_no": 'AKTU-EEE-045',
        "branch": 'EEE',
        "cgpa": 9.4,
        "gender": 'men',
        "skills": ['embedded c', 'microcontrollers', 'rtos', 'pcb design'],
        "coding_persona": 'embedded',
        "coding_score": 90.2,
        "academic_score": 90.7,
        "overall_score": 90.4,
        "has_active_backlog": False,
        "is_placed": True,
        "resume_url": 'https://demo-resumes.verifai.dev/krish-chawla.pdf',
    },
    {
        "name": 'Avantika Bose',
        "email": 'avantika.bose.demo@verifai.dev',
        "phone": '+919910000046',
        "roll_no": 'AKTU-ME-046',
        "branch": 'ME',
        "cgpa": 8.1,
        "gender": 'women',
        "skills": ['project management', 'notion', 'communication', 'analytics'],
        "coding_persona": 'product_builder',
        "coding_score": 60.4,
        "academic_score": 83.1,
        "overall_score": 69.5,
        "has_active_backlog": False,
        "is_placed": False,
        "resume_url": 'https://demo-resumes.verifai.dev/avantika-bose.pdf',
    },
    {
        "name": 'Sahil Oberoi',
        "email": 'sahil.oberoi.demo@verifai.dev',
        "phone": '+919910000047',
        "roll_no": 'AKTU-ECE-047',
        "branch": 'ECE',
        "cgpa": 9.0,
        "gender": 'men',
        "skills": ['embedded c', 'arduino', 'sensors', 'pcb design'],
        "coding_persona": 'iot_builder',
        "coding_score": 62.4,
        "academic_score": 89.8,
        "overall_score": 73.4,
        "has_active_backlog": False,
        "is_placed": False,
        "resume_url": 'https://demo-resumes.verifai.dev/sahil-oberoi.pdf',
    },
    {
        "name": 'Kiara Fernandes',
        "email": 'kiara.fernandes.demo@verifai.dev',
        "phone": '+919910000048',
        "roll_no": 'AKTU-CE-048',
        "branch": 'CE',
        "cgpa": 8.3,
        "gender": 'women',
        "skills": ['python', 'sql', 'data analysis', 'power bi'],
        "coding_persona": 'data_analyst',
        "coding_score": 67.0,
        "academic_score": 86.0,
        "overall_score": 74.6,
        "has_active_backlog": False,
        "is_placed": False,
        "resume_url": 'https://demo-resumes.verifai.dev/kiara-fernandes.pdf',
    },
    {
        "name": 'Parth Desai',
        "email": 'parth.desai.demo@verifai.dev',
        "phone": '+919910000049',
        "roll_no": 'AKTU-CSE-049',
        "branch": 'CSE',
        "cgpa": 7.8,
        "gender": 'men',
        "skills": ['python', 'c++', 'dsa', 'problem solving'],
        "coding_persona": 'competitive',
        "coding_score": 65.2,
        "academic_score": 78.3,
        "overall_score": 70.4,
        "has_active_backlog": False,
        "is_placed": False,
        "resume_url": 'https://demo-resumes.verifai.dev/parth-desai.pdf',
    },
    {
        "name": 'Naina Pillai',
        "email": 'naina.pillai.demo@verifai.dev',
        "phone": '+919910000050',
        "roll_no": 'AKTU-IT-050',
        "branch": 'IT',
        "cgpa": 8.9,
        "gender": 'women',
        "skills": ['javascript', 'react', 'node.js', 'mongodb'],
        "coding_persona": 'full_stack',
        "coding_score": 64.8,
        "academic_score": 87.5,
        "overall_score": 73.9,
        "has_active_backlog": False,
        "is_placed": False,
        "resume_url": 'https://demo-resumes.verifai.dev/naina-pillai.pdf',
    },
    {
        "name": 'Ujjwal Singh',
        "email": 'ujjwal.singh.demo@verifai.dev',
        "phone": '+919910000051',
        "roll_no": 'AKTU-AIML-051',
        "branch": 'AIML',
        "cgpa": 9.8,
        "gender": 'men',
        "skills": ['python', 'django', 'postgresql', 'redis'],
        "coding_persona": 'backend',
        "coding_score": 80.1,
        "academic_score": 95,
        "overall_score": 86.1,
        "has_active_backlog": False,
        "is_placed": False,
        "resume_url": 'https://demo-resumes.verifai.dev/ujjwal-singh.pdf',
    },
    {
        "name": 'Ayesha Khan',
        "email": 'ayesha.khan.demo@verifai.dev',
        "phone": '+919910000052',
        "roll_no": 'AKTU-DS-052',
        "branch": 'DS',
        "cgpa": 8.2,
        "gender": 'women',
        "skills": ['python', 'sql', 'data analysis', 'power bi'],
        "coding_persona": 'data_analyst',
        "coding_score": 62.1,
        "academic_score": 79.8,
        "overall_score": 69.2,
        "has_active_backlog": False,
        "is_placed": False,
        "resume_url": 'https://demo-resumes.verifai.dev/ayesha-khan.pdf',
    },
    {
        "name": 'Rudra Banerjee',
        "email": 'rudra.banerjee.demo@verifai.dev',
        "phone": '+919910000053',
        "roll_no": 'AKTU-EEE-053',
        "branch": 'EEE',
        "cgpa": 7.5,
        "gender": 'men',
        "skills": ['embedded c', 'arduino', 'sensors', 'pcb design'],
        "coding_persona": 'iot_builder',
        "coding_score": 78.0,
        "academic_score": 72.8,
        "overall_score": 75.9,
        "has_active_backlog": False,
        "is_placed": False,
        "resume_url": 'https://demo-resumes.verifai.dev/rudra-banerjee.pdf',
    },
    {
        "name": 'Jhanvi Luthra',
        "email": 'jhanvi.luthra.demo@verifai.dev',
        "phone": '+919910000054',
        "roll_no": 'AKTU-ME-054',
        "branch": 'ME',
        "cgpa": 7.1,
        "gender": 'women',
        "skills": ['excel', 'communication', 'process improvement', 'power bi'],
        "coding_persona": 'operations',
        "coding_score": 60.4,
        "academic_score": 72.0,
        "overall_score": 65.0,
        "has_active_backlog": True,
        "is_placed": False,
        "resume_url": 'https://demo-resumes.verifai.dev/jhanvi-luthra.pdf',
    },
    {
        "name": 'Abhishek Rawat',
        "email": 'abhishek.rawat.demo@verifai.dev',
        "phone": '+919910000055',
        "roll_no": 'AKTU-ECE-055',
        "branch": 'ECE',
        "cgpa": 7.2,
        "gender": 'men',
        "skills": ['embedded c', 'microcontrollers', 'rtos', 'pcb design'],
        "coding_persona": 'embedded',
        "coding_score": 88.8,
        "academic_score": 74.9,
        "overall_score": 83.2,
        "has_active_backlog": True,
        "is_placed": False,
        "resume_url": 'https://demo-resumes.verifai.dev/abhishek-rawat.pdf',
    },
    {
        "name": 'Ishita Paul',
        "email": 'ishita.paul.demo@verifai.dev',
        "phone": '+919910000056',
        "roll_no": 'AKTU-CE-056',
        "branch": 'CE',
        "cgpa": 6.6,
        "gender": 'women',
        "skills": ['project management', 'notion', 'communication', 'analytics'],
        "coding_persona": 'product_builder',
        "coding_score": 66.1,
        "academic_score": 67.4,
        "overall_score": 66.6,
        "has_active_backlog": True,
        "is_placed": False,
        "resume_url": 'https://demo-resumes.verifai.dev/ishita-paul.pdf',
    },
    {
        "name": 'Gaurav Soni',
        "email": 'gaurav.soni.demo@verifai.dev',
        "phone": '+919910000057',
        "roll_no": 'AKTU-CSE-057',
        "branch": 'CSE',
        "cgpa": 7.1,
        "gender": 'men',
        "skills": ['javascript', 'react', 'node.js', 'mongodb'],
        "coding_persona": 'full_stack',
        "coding_score": 62.5,
        "academic_score": 74.5,
        "overall_score": 67.3,
        "has_active_backlog": True,
        "is_placed": False,
        "resume_url": 'https://demo-resumes.verifai.dev/gaurav-soni.pdf',
    },
    {
        "name": 'Myra Joseph',
        "email": 'myra.joseph.demo@verifai.dev',
        "phone": '+919910000058',
        "roll_no": 'AKTU-IT-058',
        "branch": 'IT',
        "cgpa": 8.3,
        "gender": 'women',
        "skills": ['javascript', 'react', 'ui/ux design', 'figma'],
        "coding_persona": 'frontend',
        "coding_score": 74.1,
        "academic_score": 85.3,
        "overall_score": 78.6,
        "has_active_backlog": False,
        "is_placed": False,
        "resume_url": 'https://demo-resumes.verifai.dev/myra-joseph.pdf',
    },
    {
        "name": 'Tarun Nagpal',
        "email": 'tarun.nagpal.demo@verifai.dev',
        "phone": '+919910000059',
        "roll_no": 'AKTU-AIML-059',
        "branch": 'AIML',
        "cgpa": 9.1,
        "gender": 'men',
        "skills": ['python', 'pandas', 'scikit-learn', 'sql'],
        "coding_persona": 'data_scientist',
        "coding_score": 64.5,
        "academic_score": 87.8,
        "overall_score": 73.8,
        "has_active_backlog": False,
        "is_placed": False,
        "resume_url": 'https://demo-resumes.verifai.dev/tarun-nagpal.pdf',
    },
    {
        "name": 'Pallavi Reddy',
        "email": 'pallavi.reddy.demo@verifai.dev',
        "phone": '+919910000060',
        "roll_no": 'AKTU-DS-060',
        "branch": 'DS',
        "cgpa": 7.9,
        "gender": 'women',
        "skills": ['python', 'statistics', 'nlp', 'literature review'],
        "coding_persona": 'research',
        "coding_score": 72.4,
        "academic_score": 78.7,
        "overall_score": 74.9,
        "has_active_backlog": False,
        "is_placed": False,
        "resume_url": 'https://demo-resumes.verifai.dev/pallavi-reddy.pdf',
    },
    {
        "name": 'Nikhil Shetty',
        "email": 'nikhil.shetty.demo@verifai.dev',
        "phone": '+919910000061',
        "roll_no": 'AKTU-EEE-061',
        "branch": 'EEE',
        "cgpa": 8.9,
        "gender": 'men',
        "skills": ['matlab', 'autocad', 'problem solving', 'technical documentation'],
        "coding_persona": 'core_engineering',
        "coding_score": 80.9,
        "academic_score": 92.9,
        "overall_score": 85.7,
        "has_active_backlog": False,
        "is_placed": True,
        "resume_url": 'https://demo-resumes.verifai.dev/nikhil-shetty.pdf',
    },
    {
        "name": 'Zoya Mirza',
        "email": 'zoya.mirza.demo@verifai.dev',
        "phone": '+919910000062',
        "roll_no": 'AKTU-ME-062',
        "branch": 'ME',
        "cgpa": 6.7,
        "gender": 'women',
        "skills": ['matlab', 'autocad', 'problem solving', 'technical documentation'],
        "coding_persona": 'core_engineering',
        "coding_score": 71.7,
        "academic_score": 65.7,
        "overall_score": 69.3,
        "has_active_backlog": True,
        "is_placed": False,
        "resume_url": 'https://demo-resumes.verifai.dev/zoya-mirza.pdf',
    },
    {
        "name": 'Chirag Anand',
        "email": 'chirag.anand.demo@verifai.dev',
        "phone": '+919910000063',
        "roll_no": 'AKTU-ECE-063',
        "branch": 'ECE',
        "cgpa": 9.3,
        "gender": 'men',
        "skills": ['python', 'django', 'postgresql', 'redis'],
        "coding_persona": 'backend',
        "coding_score": 66.5,
        "academic_score": 90.5,
        "overall_score": 76.1,
        "has_active_backlog": False,
        "is_placed": False,
        "resume_url": 'https://demo-resumes.verifai.dev/chirag-anand.pdf',
    },
    {
        "name": 'Prisha Kohli',
        "email": 'prisha.kohli.demo@verifai.dev',
        "phone": '+919910000064',
        "roll_no": 'AKTU-CE-064',
        "branch": 'CE',
        "cgpa": 7.9,
        "gender": 'women',
        "skills": ['excel', 'communication', 'process improvement', 'power bi'],
        "coding_persona": 'operations',
        "coding_score": 72.3,
        "academic_score": 77.2,
        "overall_score": 74.3,
        "has_active_backlog": False,
        "is_placed": False,
        "resume_url": 'https://demo-resumes.verifai.dev/prisha-kohli.pdf',
    },
    {
        "name": 'Anmol Bedi',
        "email": 'anmol.bedi.demo@verifai.dev',
        "phone": '+919910000065',
        "roll_no": 'AKTU-CSE-065',
        "branch": 'CSE',
        "cgpa": 7.2,
        "gender": 'men',
        "skills": ['python', 'django', 'postgresql', 'redis'],
        "coding_persona": 'backend',
        "coding_score": 89.4,
        "academic_score": 71.5,
        "overall_score": 82.2,
        "has_active_backlog": False,
        "is_placed": True,
        "resume_url": 'https://demo-resumes.verifai.dev/anmol-bedi.pdf',
    },
    {
        "name": 'Mahi Tandon',
        "email": 'mahi.tandon.demo@verifai.dev',
        "phone": '+919910000066',
        "roll_no": 'AKTU-IT-066',
        "branch": 'IT',
        "cgpa": 9.3,
        "gender": 'women',
        "skills": ['project management', 'notion', 'communication', 'analytics'],
        "coding_persona": 'product_builder',
        "coding_score": 76.7,
        "academic_score": 89.4,
        "overall_score": 81.8,
        "has_active_backlog": True,
        "is_placed": False,
        "resume_url": 'https://demo-resumes.verifai.dev/mahi-tandon.pdf',
    },
    {
        "name": 'Varun Solanki',
        "email": 'varun.solanki.demo@verifai.dev',
        "phone": '+919910000067',
        "roll_no": 'AKTU-AIML-067',
        "branch": 'AIML',
        "cgpa": 9.8,
        "gender": 'men',
        "skills": ['python', 'pytorch', 'mlops', 'docker'],
        "coding_persona": 'ml_engineer',
        "coding_score": 86.4,
        "academic_score": 95,
        "overall_score": 89.8,
        "has_active_backlog": False,
        "is_placed": False,
        "resume_url": 'https://demo-resumes.verifai.dev/varun-solanki.pdf',
    },
    {
        "name": 'Sara Mathew',
        "email": 'sara.mathew.demo@verifai.dev',
        "phone": '+919910000068',
        "roll_no": 'AKTU-DS-068',
        "branch": 'DS',
        "cgpa": 9.5,
        "gender": 'women',
        "skills": ['python', 'pytorch', 'mlops', 'docker'],
        "coding_persona": 'ml_engineer',
        "coding_score": 86.9,
        "academic_score": 92.3,
        "overall_score": 89.1,
        "has_active_backlog": False,
        "is_placed": True,
        "resume_url": 'https://demo-resumes.verifai.dev/sara-mathew.pdf',
    },
    {
        "name": 'Hemant Jha',
        "email": 'hemant.jha.demo@verifai.dev',
        "phone": '+919910000069',
        "roll_no": 'AKTU-EEE-069',
        "branch": 'EEE',
        "cgpa": 8.1,
        "gender": 'men',
        "skills": ['embedded c', 'microcontrollers', 'rtos', 'pcb design'],
        "coding_persona": 'embedded',
        "coding_score": 65.3,
        "academic_score": 80.2,
        "overall_score": 71.3,
        "has_active_backlog": False,
        "is_placed": False,
        "resume_url": 'https://demo-resumes.verifai.dev/hemant-jha.pdf',
    },
    {
        "name": 'Lavanya Rao',
        "email": 'lavanya.rao.demo@verifai.dev',
        "phone": '+919910000070',
        "roll_no": 'AKTU-ME-070',
        "branch": 'ME',
        "cgpa": 6.6,
        "gender": 'women',
        "skills": ['project management', 'notion', 'communication', 'analytics'],
        "coding_persona": 'product_builder',
        "coding_score": 70.9,
        "academic_score": 69.9,
        "overall_score": 70.5,
        "has_active_backlog": True,
        "is_placed": False,
        "resume_url": 'https://demo-resumes.verifai.dev/lavanya-rao.pdf',
    },
    {
        "name": 'Akash Dixit',
        "email": 'akash.dixit.demo@verifai.dev',
        "phone": '+919910000071',
        "roll_no": 'AKTU-ECE-071',
        "branch": 'ECE',
        "cgpa": 7.3,
        "gender": 'men',
        "skills": ['embedded c', 'arduino', 'sensors', 'pcb design'],
        "coding_persona": 'iot_builder',
        "coding_score": 84.7,
        "academic_score": 72.6,
        "overall_score": 79.9,
        "has_active_backlog": False,
        "is_placed": False,
        "resume_url": 'https://demo-resumes.verifai.dev/akash-dixit.pdf',
    },
    {
        "name": 'Bhavya Arora',
        "email": 'bhavya.arora.demo@verifai.dev',
        "phone": '+919910000072',
        "roll_no": 'AKTU-CE-072',
        "branch": 'CE',
        "cgpa": 7.8,
        "gender": 'women',
        "skills": ['python', 'sql', 'data analysis', 'power bi'],
        "coding_persona": 'data_analyst',
        "coding_score": 90.5,
        "academic_score": 82.0,
        "overall_score": 87.1,
        "has_active_backlog": False,
        "is_placed": True,
        "resume_url": 'https://demo-resumes.verifai.dev/bhavya-arora.pdf',
    },
    {
        "name": 'Chetan Sagar',
        "email": 'chetan.sagar.demo@verifai.dev',
        "phone": '+919910000073',
        "roll_no": 'AKTU-CSE-073',
        "branch": 'CSE',
        "cgpa": 8.3,
        "gender": 'men',
        "skills": ['python', 'c++', 'dsa', 'problem solving'],
        "coding_persona": 'competitive',
        "coding_score": 82.4,
        "academic_score": 80.2,
        "overall_score": 81.5,
        "has_active_backlog": False,
        "is_placed": True,
        "resume_url": 'https://demo-resumes.verifai.dev/chetan-sagar.pdf',
    },
    {
        "name": 'Nupur Ghosh',
        "email": 'nupur.ghosh.demo@verifai.dev',
        "phone": '+919910000074',
        "roll_no": 'AKTU-IT-074',
        "branch": 'IT',
        "cgpa": 7.4,
        "gender": 'women',
        "skills": ['javascript', 'react', 'node.js', 'mongodb'],
        "coding_persona": 'full_stack',
        "coding_score": 90.9,
        "academic_score": 74.6,
        "overall_score": 84.4,
        "has_active_backlog": False,
        "is_placed": False,
        "resume_url": 'https://demo-resumes.verifai.dev/nupur-ghosh.pdf',
    },
    {
        "name": 'Madhav Batra',
        "email": 'madhav.batra.demo@verifai.dev',
        "phone": '+919910000075',
        "roll_no": 'AKTU-AIML-075',
        "branch": 'AIML',
        "cgpa": 8.2,
        "gender": 'men',
        "skills": ['python', 'django', 'postgresql', 'redis'],
        "coding_persona": 'backend',
        "coding_score": 83.4,
        "academic_score": 78.5,
        "overall_score": 81.4,
        "has_active_backlog": False,
        "is_placed": False,
        "resume_url": 'https://demo-resumes.verifai.dev/madhav-batra.pdf',
    },
    {
        "name": 'Ishani Vora',
        "email": 'ishani.vora.demo@verifai.dev',
        "phone": '+919910000076',
        "roll_no": 'AKTU-DS-076',
        "branch": 'DS',
        "cgpa": 8.4,
        "gender": 'women',
        "skills": ['python', 'sql', 'data analysis', 'power bi'],
        "coding_persona": 'data_analyst',
        "coding_score": 75.1,
        "academic_score": 86.8,
        "overall_score": 79.8,
        "has_active_backlog": False,
        "is_placed": True,
        "resume_url": 'https://demo-resumes.verifai.dev/ishani-vora.pdf',
    },
    {
        "name": 'Raghav Suri',
        "email": 'raghav.suri.demo@verifai.dev',
        "phone": '+919910000077',
        "roll_no": 'AKTU-EEE-077',
        "branch": 'EEE',
        "cgpa": 6.9,
        "gender": 'men',
        "skills": ['embedded c', 'arduino', 'sensors', 'pcb design'],
        "coding_persona": 'iot_builder',
        "coding_score": 90.7,
        "academic_score": 65.6,
        "overall_score": 80.7,
        "has_active_backlog": True,
        "is_placed": False,
        "resume_url": 'https://demo-resumes.verifai.dev/raghav-suri.pdf',
    },
    {
        "name": 'Pihu Walia',
        "email": 'pihu.walia.demo@verifai.dev',
        "phone": '+919910000078',
        "roll_no": 'AKTU-ME-078',
        "branch": 'ME',
        "cgpa": 7.0,
        "gender": 'women',
        "skills": ['excel', 'communication', 'process improvement', 'power bi'],
        "coding_persona": 'operations',
        "coding_score": 78.2,
        "academic_score": 71.4,
        "overall_score": 75.5,
        "has_active_backlog": True,
        "is_placed": False,
        "resume_url": 'https://demo-resumes.verifai.dev/pihu-walia.pdf',
    },
    {
        "name": 'Vihaan Narula',
        "email": 'vihaan.narula.demo@verifai.dev',
        "phone": '+919910000079',
        "roll_no": 'AKTU-ECE-079',
        "branch": 'ECE',
        "cgpa": 7.2,
        "gender": 'men',
        "skills": ['embedded c', 'microcontrollers', 'rtos', 'pcb design'],
        "coding_persona": 'embedded',
        "coding_score": 62.1,
        "academic_score": 75.1,
        "overall_score": 67.3,
        "has_active_backlog": False,
        "is_placed": False,
        "resume_url": 'https://demo-resumes.verifai.dev/vihaan-narula.pdf',
    },
    {
        "name": 'Aarohi Khandelwal',
        "email": 'aarohi.khandelwal.demo@verifai.dev',
        "phone": '+919910000080',
        "roll_no": 'AKTU-CE-080',
        "branch": 'CE',
        "cgpa": 7.2,
        "gender": 'women',
        "skills": ['project management', 'notion', 'communication', 'analytics'],
        "coding_persona": 'product_builder',
        "coding_score": 78.2,
        "academic_score": 73.0,
        "overall_score": 76.1,
        "has_active_backlog": False,
        "is_placed": False,
        "resume_url": 'https://demo-resumes.verifai.dev/aarohi-khandelwal.pdf',
    },
    {
        "name": 'Kunal Bakshi',
        "email": 'kunal.bakshi.demo@verifai.dev',
        "phone": '+919910000081',
        "roll_no": 'AKTU-CSE-081',
        "branch": 'CSE',
        "cgpa": 7.8,
        "gender": 'men',
        "skills": ['javascript', 'react', 'node.js', 'mongodb'],
        "coding_persona": 'full_stack',
        "coding_score": 77.8,
        "academic_score": 78.2,
        "overall_score": 78.0,
        "has_active_backlog": False,
        "is_placed": False,
        "resume_url": 'https://demo-resumes.verifai.dev/kunal-bakshi.pdf',
    },
    {
        "name": 'Trisha Nambiar',
        "email": 'trisha.nambiar.demo@verifai.dev',
        "phone": '+919910000082',
        "roll_no": 'AKTU-IT-082',
        "branch": 'IT',
        "cgpa": 9.6,
        "gender": 'women',
        "skills": ['javascript', 'react', 'ui/ux design', 'figma'],
        "coding_persona": 'frontend',
        "coding_score": 64.9,
        "academic_score": 95,
        "overall_score": 76.9,
        "has_active_backlog": False,
        "is_placed": False,
        "resume_url": 'https://demo-resumes.verifai.dev/trisha-nambiar.pdf',
    },
    {
        "name": 'Mohit Sehgal',
        "email": 'mohit.sehgal.demo@verifai.dev',
        "phone": '+919910000083',
        "roll_no": 'AKTU-AIML-083',
        "branch": 'AIML',
        "cgpa": 7.2,
        "gender": 'men',
        "skills": ['python', 'pandas', 'scikit-learn', 'sql'],
        "coding_persona": 'data_scientist',
        "coding_score": 71.5,
        "academic_score": 73.4,
        "overall_score": 72.3,
        "has_active_backlog": False,
        "is_placed": False,
        "resume_url": 'https://demo-resumes.verifai.dev/mohit-sehgal.pdf',
    },
    {
        "name": 'Saloni Dubey',
        "email": 'saloni.dubey.demo@verifai.dev',
        "phone": '+919910000084',
        "roll_no": 'AKTU-DS-084',
        "branch": 'DS',
        "cgpa": 7.4,
        "gender": 'women',
        "skills": ['python', 'statistics', 'nlp', 'literature review'],
        "coding_persona": 'research',
        "coding_score": 68.8,
        "academic_score": 76.0,
        "overall_score": 71.7,
        "has_active_backlog": False,
        "is_placed": False,
        "resume_url": 'https://demo-resumes.verifai.dev/saloni-dubey.pdf',
    },
    {
        "name": 'Jatin Ahuja',
        "email": 'jatin.ahuja.demo@verifai.dev',
        "phone": '+919910000085',
        "roll_no": 'AKTU-EEE-085',
        "branch": 'EEE',
        "cgpa": 6.6,
        "gender": 'men',
        "skills": ['matlab', 'autocad', 'problem solving', 'technical documentation'],
        "coding_persona": 'core_engineering',
        "coding_score": 73.6,
        "academic_score": 70.0,
        "overall_score": 72.2,
        "has_active_backlog": True,
        "is_placed": False,
        "resume_url": 'https://demo-resumes.verifai.dev/jatin-ahuja.pdf',
    },
    {
        "name": 'Yukti Kapoor',
        "email": 'yukti.kapoor.demo@verifai.dev',
        "phone": '+919910000086',
        "roll_no": 'AKTU-ME-086',
        "branch": 'ME',
        "cgpa": 9.8,
        "gender": 'women',
        "skills": ['matlab', 'autocad', 'problem solving', 'technical documentation'],
        "coding_persona": 'core_engineering',
        "coding_score": 60.5,
        "academic_score": 95,
        "overall_score": 74.3,
        "has_active_backlog": False,
        "is_placed": False,
        "resume_url": 'https://demo-resumes.verifai.dev/yukti-kapoor.pdf',
    },
    {
        "name": 'Ritesh Parmar',
        "email": 'ritesh.parmar.demo@verifai.dev',
        "phone": '+919910000087',
        "roll_no": 'AKTU-ECE-087',
        "branch": 'ECE',
        "cgpa": 7.3,
        "gender": 'men',
        "skills": ['python', 'django', 'postgresql', 'redis'],
        "coding_persona": 'backend',
        "coding_score": 89.7,
        "academic_score": 76.0,
        "overall_score": 84.2,
        "has_active_backlog": False,
        "is_placed": False,
        "resume_url": 'https://demo-resumes.verifai.dev/ritesh-parmar.pdf',
    },
    {
        "name": 'Niharika Rao',
        "email": 'niharika.rao.demo@verifai.dev',
        "phone": '+919910000088',
        "roll_no": 'AKTU-CE-088',
        "branch": 'CE',
        "cgpa": 9.4,
        "gender": 'women',
        "skills": ['excel', 'communication', 'process improvement', 'power bi'],
        "coding_persona": 'operations',
        "coding_score": 70.6,
        "academic_score": 91.3,
        "overall_score": 78.9,
        "has_active_backlog": True,
        "is_placed": False,
        "resume_url": 'https://demo-resumes.verifai.dev/niharika-rao.pdf',
    },
    {
        "name": 'Nitin George',
        "email": 'nitin.george.demo@verifai.dev',
        "phone": '+919910000089',
        "roll_no": 'AKTU-CSE-089',
        "branch": 'CSE',
        "cgpa": 9.2,
        "gender": 'men',
        "skills": ['python', 'django', 'postgresql', 'redis'],
        "coding_persona": 'backend',
        "coding_score": 81.9,
        "academic_score": 92.9,
        "overall_score": 86.3,
        "has_active_backlog": False,
        "is_placed": True,
        "resume_url": 'https://demo-resumes.verifai.dev/nitin-george.pdf',
    },
    {
        "name": 'Sanika Patil',
        "email": 'sanika.patil.demo@verifai.dev',
        "phone": '+919910000090',
        "roll_no": 'AKTU-IT-090',
        "branch": 'IT',
        "cgpa": 9.8,
        "gender": 'women',
        "skills": ['project management', 'notion', 'communication', 'analytics'],
        "coding_persona": 'product_builder',
        "coding_score": 80.2,
        "academic_score": 94.1,
        "overall_score": 85.8,
        "has_active_backlog": False,
        "is_placed": False,
        "resume_url": 'https://demo-resumes.verifai.dev/sanika-patil.pdf',
    },
    {
        "name": 'Reyansh Sinha',
        "email": 'reyansh.sinha.demo@verifai.dev',
        "phone": '+919910000091',
        "roll_no": 'AKTU-AIML-091',
        "branch": 'AIML',
        "cgpa": 9.2,
        "gender": 'men',
        "skills": ['python', 'pytorch', 'mlops', 'docker'],
        "coding_persona": 'ml_engineer',
        "coding_score": 68.2,
        "academic_score": 93.3,
        "overall_score": 78.2,
        "has_active_backlog": False,
        "is_placed": False,
        "resume_url": 'https://demo-resumes.verifai.dev/reyansh-sinha.pdf',
    },
    {
        "name": 'Charvi Mallick',
        "email": 'charvi.mallick.demo@verifai.dev',
        "phone": '+919910000092',
        "roll_no": 'AKTU-DS-092',
        "branch": 'DS',
        "cgpa": 9.6,
        "gender": 'women',
        "skills": ['python', 'pytorch', 'mlops', 'docker'],
        "coding_persona": 'ml_engineer',
        "coding_score": 62.6,
        "academic_score": 92.9,
        "overall_score": 74.7,
        "has_active_backlog": False,
        "is_placed": False,
        "resume_url": 'https://demo-resumes.verifai.dev/charvi-mallick.pdf',
    },
    {
        "name": 'Aryan Thakur',
        "email": 'aryan.thakur.demo@verifai.dev',
        "phone": '+919910000093',
        "roll_no": 'AKTU-EEE-093',
        "branch": 'EEE',
        "cgpa": 6.8,
        "gender": 'men',
        "skills": ['embedded c', 'microcontrollers', 'rtos', 'pcb design'],
        "coding_persona": 'embedded',
        "coding_score": 76.8,
        "academic_score": 66.2,
        "overall_score": 72.6,
        "has_active_backlog": True,
        "is_placed": False,
        "resume_url": 'https://demo-resumes.verifai.dev/aryan-thakur.pdf',
    },
    {
        "name": 'Siya Chandra',
        "email": 'siya.chandra.demo@verifai.dev',
        "phone": '+919910000094',
        "roll_no": 'AKTU-ME-094',
        "branch": 'ME',
        "cgpa": 8.5,
        "gender": 'women',
        "skills": ['project management', 'notion', 'communication', 'analytics'],
        "coding_persona": 'product_builder',
        "coding_score": 82.4,
        "academic_score": 82.6,
        "overall_score": 82.5,
        "has_active_backlog": False,
        "is_placed": False,
        "resume_url": 'https://demo-resumes.verifai.dev/siya-chandra.pdf',
    },
]


PROJECT_CATALOG: list[tuple[str, list[str]]] = [
    ("Campus Placement Predictor", ["python", "fastapi", "postgresql", "docker"]),
    ("Resume Screening Assistant", ["python", "nlp", "react", "mongodb"]),
    ("Attendance Dashboard", ["javascript", "react", "nodejs", "postgresql"]),
    ("Issue Tracker", ["typescript", "nextjs", "nodejs", "mongodb"]),
    ("Analytics Workbench", ["python", "sql", "power bi", "pandas"]),
    ("IoT Monitoring Portal", ["embedded c", "arduino", "sensors", "javascript"]),
]

EXPERIENCE_TEMPLATES: list[str] = [
    "Built APIs and backend jobs for student-facing workflow automation.",
    "Improved dashboard responsiveness and reduced loading time with targeted optimizations.",
    "Collaborated on feature delivery using sprint planning, code reviews, and Git workflows.",
    "Added data quality checks and validation utilities for recruiter-facing reports.",
]


def _deterministic_rng(entry: dict) -> random.Random:
    seed_material = f"{entry['email']}|{entry['roll_no']}|{entry['coding_score']}|{entry['cgpa']}"
    digest = hashlib.sha256(seed_material.encode("utf-8")).hexdigest()
    seed = int(digest[:16], 16)
    return random.Random(seed)


def _build_resume_data(entry: dict, rng: random.Random) -> dict:
    base_skills = [str(skill).strip().lower() for skill in entry["skills"] if str(skill).strip()]
    project_count = 2 if entry["coding_score"] >= 72 else 1
    projects: list[dict] = []
    for _ in range(project_count):
        title, stack = rng.choice(PROJECT_CATALOG)
        tech_stack = list(dict.fromkeys((base_skills[:2] + rng.sample(stack, k=min(2, len(stack))))))[:4]
        projects.append(
            {
                "title": title,
                "description": f"{title} implementation for academic and placement-focused use cases.",
                "tech_stack": tech_stack,
            }
        )

    exp_count = 2 if entry["coding_score"] >= 80 else 1
    experience: list[dict] = []
    for _ in range(exp_count):
        experience.append(
            {
                "title": rng.choice(["Software Developer Intern", "Project Trainee", "Backend Intern"]),
                "impact": rng.choice(EXPERIENCE_TEMPLATES),
                "tech_stack": list(dict.fromkeys(rng.sample(base_skills, k=min(3, len(base_skills))))),
            }
        )

    return {
        "file_name": f"{entry['roll_no'].lower()}.pdf",
        "summary": f"Demo resume for {entry['name']}",
        "skills": base_skills,
        "projects": projects,
        "experience": experience,
        "metadata": {
            "has_active_backlog": entry["has_active_backlog"],
            "is_placed": entry["is_placed"],
        },
    }


def _build_academic_data(entry: dict) -> dict:
    return {
        "cgpa_computed": entry["cgpa"],
        "cgpa": entry["cgpa"],
        "has_active_backlog": entry["has_active_backlog"],
    }


def _build_github_data(entry: dict, rng: random.Random) -> dict:
    normalized_skills = [str(skill).strip().lower() for skill in entry["skills"] if str(skill).strip()]
    coding_score = float(entry["coding_score"])
    repos = max(4, min(28, int(coding_score / 3) + rng.randint(0, 4)))
    commits_30d = max(6, min(95, int(coding_score * 0.85) + rng.randint(-6, 10)))
    followers = max(3, int(repos * 1.8) + rng.randint(0, 25))

    repo_count = 3 if coding_score >= 75 else 2
    repositories: list[dict] = []
    for idx in range(repo_count):
        title, stack = rng.choice(PROJECT_CATALOG)
        tech_stack = list(dict.fromkeys((normalized_skills[:2] + stack)))[:4]
        repositories.append(
            {
                "name": f"{title.lower().replace(' ', '-')}-{idx + 1}",
                "language": tech_stack[0] if tech_stack else "python",
                "tech_stack": tech_stack,
                "stars": max(2, int(coding_score / 8) + rng.randint(0, 15)),
            }
        )

    return {
        "username": entry["roll_no"].lower().replace("-", "_"),
        "repos": repos,
        "public_repos": repos,
        "followers": followers,
        "last_30_day_commits": commits_30d,
        "recent_commit_activity": commits_30d,
        "languages": list(dict.fromkeys(normalized_skills[:3])),
        "repositories": repositories,
        "pinned_repositories": repositories[:2],
    }


def _build_leetcode_data(entry: dict, rng: random.Random) -> dict:
    coding_score = float(entry["coding_score"])
    solved = max(60, min(520, int(coding_score * 4.8) + rng.randint(-20, 25)))
    hard = max(8, int(solved * (0.10 + rng.uniform(0.02, 0.06))))
    medium = max(30, int(solved * (0.34 + rng.uniform(0.03, 0.08))))
    easy = max(20, solved - medium - hard)
    contest_count = max(3, min(26, int(coding_score / 4) + rng.randint(0, 4)))
    contest_rating = max(1280, min(2120, int(1280 + (coding_score * 7.8) + rng.randint(-60, 75))))

    return {
        "username": entry["roll_no"].lower().replace("-", ""),
        "total_solved": solved,
        "totalSolved": solved,
        "easy": easy,
        "medium": medium,
        "hard": hard,
        "contest_rating": contest_rating,
        "rating": contest_rating,
        "contest_participation_count": contest_count,
    }


def reset_demo_tables() -> None:
    with SessionLocal() as db:
        db.execute(text("TRUNCATE TABLE raw_uploads, student_profiles, students RESTART IDENTITY CASCADE"))
        db.commit()



def upsert_demo_students() -> None:
    now = datetime.now(UTC)
    with SessionLocal() as db:
        for entry in DEMO_STUDENTS:
            rng = _deterministic_rng(entry)
            student = db.query(Student).filter(Student.email == entry["email"]).one_or_none()
            if student is None:
                student = Student(
                    name=entry["name"],
                    email=entry["email"],
                    roll_no=entry["roll_no"],
                    password_hash="",
                    phone=entry["phone"],
                    branch=entry["branch"],
                    cgpa=entry["cgpa"],
                    gender=entry["gender"],
                    cgpa_verified=True,
                )
                db.add(student)
                db.flush()
            else:
                student.name = entry["name"]
                student.roll_no = entry["roll_no"]
                student.phone = entry["phone"]
                student.branch = entry["branch"]
                student.cgpa = entry["cgpa"]
                student.gender = entry["gender"]
                student.cgpa_verified = True

            profile = db.query(StudentProfile).filter(StudentProfile.student_id == student.id).one_or_none()
            resume_data = _build_resume_data(entry, rng)
            academic_data = _build_academic_data(entry)
            github_data = _build_github_data(entry, rng)
            leetcode_data = _build_leetcode_data(entry, rng)

            if profile is None:
                profile = StudentProfile(
                    student_id=student.id,
                    skills=entry["skills"],
                    coding_persona=entry["coding_persona"],
                    coding_score=entry["coding_score"],
                    academic_score=entry["academic_score"],
                    overall_score=entry["overall_score"],
                    github_data=github_data,
                    leetcode_data=leetcode_data,
                    resume_data=resume_data,
                    academic_data=academic_data,
                    last_analyzed_at=now,
                )
                db.add(profile)
            else:
                profile.skills = entry["skills"]
                profile.coding_persona = entry["coding_persona"]
                profile.coding_score = entry["coding_score"]
                profile.academic_score = entry["academic_score"]
                profile.overall_score = entry["overall_score"]
                profile.github_data = github_data
                profile.leetcode_data = leetcode_data
                profile.resume_data = resume_data
                profile.academic_data = academic_data
                profile.last_analyzed_at = now

            raw_upload = db.query(RawUpload).filter(RawUpload.student_id == student.id).one_or_none()
            if raw_upload is None:
                raw_upload = RawUpload(
                    student_id=student.id,
                    resume_url=entry["resume_url"],
                    marksheet_url=None,
                )
                db.add(raw_upload)
            else:
                raw_upload.resume_url = entry["resume_url"]
                raw_upload.marksheet_url = None
                raw_upload.uploaded_at = now

        db.commit()


if __name__ == "__main__":
    reset_demo_tables()
    upsert_demo_students()
    print(f"Seeded {len(DEMO_STUDENTS)} demo students.")